apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::334831876780:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1B7K2R395FLXJ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::334831876780:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-19T02:59:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5504"
  uid: 2bdf993d-7497-4c35-a866-e37e7269c064
